name: Deploy Flask API with Tests

env:
  HEROKU_APP_NAME: api-bank               # nom de votre application Heroku
  PYTHON_VERSION: '3.10'                   # version de Python à utiliser

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Set up dependency caching for faster installs
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

    #  - name: Run unit tests
    #    run: |
    #      source venv/bin/activate
          # Remplacez par la commande de test appropriée (ex: pytest)
         # pytest

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.9
        with:
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
