name: Deploy Flask API with Tests

on:
  push:
    branches:
      - main  # Déclenche le déploiement sur les push vers la branche main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v3  # Mettez à jour à v3

      - name: Configurer Python
        uses: actions/setup-python@v3  # Mettez à jour à v3
        with:
          python-version: '3.8'  # Changez cette version si nécessaire

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter les tests
        run: |
          pytest